
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ import { Address } from "./Address";
/* do not edit */ 
/* do not edit */ export interface Addresses {
/* do not edit */     [devieSourceId: string]: Address[];
/* do not edit */ }