
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ import { User } from "./User";
/* do not edit */
/* do not edit */ export interface AuthenticateSuccessResponse {
/* do not edit */     access_token: string;
/* do not edit */     user: User;
/* do not edit */ }