
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface CloudListenerSocketData {
/* do not edit */     id: string;
/* do not edit */     socketId: string;
/* do not edit */     deviceId: string;
/* do not edit */     listenerType: string;
/* do not edit */     ipAddress: string;
/* do not edit */     datetimeConnected: string;
/* do not edit */     inactive: boolean;
/* do not edit */
/* do not edit */     cloudConnection?: boolean;
/* do not edit */     cloudClientId?: string;
/* do not edit */ }