
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ import { Socket } from 'socket.io-client';
/* do not edit */
/* do not edit */ export interface CloudDestinationSocket {
/* do not edit */     id: string;
/* do not edit */     socket: Socket;
/* do not edit */     host: string;
/* do not edit */     port: string;
/* do not edit */     key: string;
/* do not edit */
/* do not edit */     connected?: boolean;
/* do not edit */     error?: boolean;
/* do not edit */ }