
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface ConfigSecuritySection {
/* do not edit */     jwt_private_key: string;
/* do not edit */
/* do not edit */     //here for compatibility with old config
/* do not edit */     username_settings?: string;
/* do not edit */     password_settings?: string;
/* do not edit */     username_producer?: string;
/* do not edit */     password_producer?: string;
/* do not edit */ }