
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ import { BusOption } from "./BusOption";
/* do not edit */ import { CloudDestination } from "./CloudDestination";
/* do not edit */ import { ConfigSecuritySection } from "./ConfigSecuritySection";
/* do not edit */ import { User } from "./User";
/* do not edit */ import { ConfigTSLClient } from "./ConfigTSLClient";
/* do not edit */ import { Device } from "./Device";
/* do not edit */ import { DeviceAction } from "./DeviceAction";
/* do not edit */ import { DeviceSource } from "./DeviceSource";
/* do not edit */ import { Source } from "./Source";
/* do not edit */
/* do not edit */ export interface Config {
/* do not edit */     externalAddress: string;
/* do not edit */     uuid: string;
/* do not edit */     security: ConfigSecuritySection;
/* do not edit */     users: User[];
/* do not edit */     sources: Source[];
/* do not edit */     devices: Device[];
/* do not edit */     device_sources: DeviceSource[];
/* do not edit */     device_actions: DeviceAction[];
/* do not edit */     tsl_clients: ConfigTSLClient[];
/* do not edit */     tsl_clients_1secupdate: boolean;
/* do not edit */     cloud_destinations: CloudDestination[];
/* do not edit */     cloud_keys: string[];
/* do not edit */     bus_options: BusOption[];
/* do not edit */     remoteErrorReporting: boolean;
/* do not edit */ }