
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface ConfigTSLClient {
/* do not edit */     id: string;
/* do not edit */     ip: string;
/* do not edit */     port: number | string;
/* do not edit */     transport: string;
/* do not edit */ }