
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface ManageResponse {
/* do not edit */     result: string;
/* do not edit */     deviceId?: string;
/* do not edit */     error?: 'Invalid API request.' | string;
/* do not edit */ }