
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ import { BusOption } from "./BusOption";
/* do not edit */ import { CloudDestination } from "./CloudDestination";
/* do not edit */ import { Device } from "./Device";
/* do not edit */ import { DeviceAction } from "./DeviceAction";
/* do not edit */ import { DeviceSource } from "./DeviceSource";
/* do not edit */ import { Source } from "./Source";
/* do not edit */ import { TSLClient } from "./TSLClient";
/* do not edit */ import { User } from "./User";
/* do not edit */
/* do not edit */ export interface Manage {
/* do not edit */     type: 'source' | 'device' | 'device_source' | 'device_action' | 'tsl_client' | 'bus_option' | 'cloud_destination' | 'cloud_key' | 'cloud_client' | 'user';
/* do not edit */     action: 'add' | 'edit' | 'delete' | 'remove';
/* do not edit */
/* do not edit */     source?: Source;
/* do not edit */     sourceId?: string;
/* do not edit */     device?: Device;
/* do not edit */     deviceId?: string;
/* do not edit */     device_source?: DeviceSource;
/* do not edit */     device_action?: DeviceAction;
/* do not edit */     tslClient?: TSLClient;
/* do not edit */     tslClientId: string;
/* do not edit */     busOption?: BusOption;
/* do not edit */     busOptionId?: string;
/* do not edit */     cloudDestination?: CloudDestination;
/* do not edit */     cloudId?: string;
/* do not edit */     key?: string;
/* do not edit */     id?: string;
/* do not edit */     user?: User;
/* do not edit */ }