
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface MessageListenerClientResponse {
/* do not edit */     result: 'message-sent-successfully' | 'message-not-sent';
/* do not edit */     listenerClientId: string | { relayGroupId?: string; gpoGroupId?: string };
/* do not edit */     error?: 'listener-client-not-supported' | 'listener-client-not-found';
/* do not edit */ }