
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface Message {
/* do not edit */     type: "producer" | "client" | "server";
/* do not edit */     socketId: string;
/* do not edit */     text: string;
/* do not edit */     date: Date;
/* do not edit */ }