
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */ export interface NetworkDiscovery {
/* do not edit */     sourceId: string;
/* do not edit */
/* do not edit */     name: string;
/* do not edit */     addresses: string[];
/* do not edit */     ip?: string;
/* do not edit */     port?: number;
/* do not edit */ }