// this file is automatically generated by git.version.js script
export const versions = {
  revision: '1bd3925',
  branch: 'main',
  remote_url: 'https://github.com/Hirates/Helios-Grizzlys-Tally.git'
};